import test from 'node:test';
import assert from 'node:assert';
import { PrismaClient } from '@prisma/client';
import { PayrollRunService } from '../services/payroll-run.service.js';
import { PayrollEngine } from '../services/payroll.engine.js';
import { PaymentService } from '../services/payment.service.js';
import { AccountingService } from '../services/accounting.service.js';
import { ReconciliationService } from '../services/reconciliation.service.js';
import { PayslipService } from '../services/payslip.service.js';
import { ReportService } from '../services/report.service.js';
import { EssService } from '../services/ess.service.js';
import { FinanceAnalyticsService } from '../services/analytics.service.js';

const prisma = new PrismaClient();

test('Full System E2E E2E Workflow', async (t) => {
  let tenantA: any;
  let tenantB: any;
  let empA: any;
  let empB: any;
  let runPeriodMonth = 11;
  let runPeriodYear = 2026;
  
  await t.test('1. Setup Organizations and Employees', async () => {
    tenantA = await prisma.tenant.create({ data: { name: 'E2E Tenant A' } });
    tenantB = await prisma.tenant.create({ data: { name: 'E2E Tenant B' } });
    
    empA = await prisma.employee.create({ data: { tenantId: tenantA.id, employeeId: 'E2E-A', firstName: 'Alice', lastName: 'A', status: 'ACTIVE' } });
    empB = await prisma.employee.create({ data: { tenantId: tenantB.id, employeeId: 'E2E-B', firstName: 'Bob', lastName: 'B', status: 'ACTIVE' } });

    await prisma.employeeBank.create({ data: { employeeId: empA.id, accountNumber: 'ACC123', ifscCode: 'IFSC123', bankName: 'Test Bank' } });
  });

  await t.test('2. Setup Compensation & Formula Engine', async () => {
    const compBasic = await prisma.salaryComponent.create({ data: { tenantId: tenantA.id, name: 'Basic', code: 'BASIC', type: 'EARNING' } });
    const compHra = await prisma.salaryComponent.create({ data: { tenantId: tenantA.id, name: 'HRA', code: 'HRA', type: 'EARNING' } });
    const compPf = await prisma.salaryComponent.create({ data: { tenantId: tenantA.id, name: 'PF', code: 'PF', type: 'DEDUCTION' } });

    await prisma.salaryFormula.create({ data: { tenantId: tenantA.id, salaryComponentId: compBasic.id, expression: '(CTC * 0.4) / 12' } });
    await prisma.salaryFormula.create({ data: { tenantId: tenantA.id, salaryComponentId: compHra.id, expression: '(CTC * 0.2) / 12' } });
    await prisma.salaryFormula.create({ data: { tenantId: tenantA.id, salaryComponentId: compPf.id, expression: 'BASIC * 0.12' } });

    const struct = await prisma.salaryStructure.create({ data: { tenantId: tenantA.id, name: 'E2E Structure' } });
    await prisma.salaryStructureComponent.create({ data: { salaryStructureId: struct.id, salaryComponentId: compBasic.id } });
    await prisma.salaryStructureComponent.create({ data: { salaryStructureId: struct.id, salaryComponentId: compHra.id } });
    await prisma.salaryStructureComponent.create({ data: { salaryStructureId: struct.id, salaryComponentId: compPf.id } });

    await prisma.salaryRevision.create({ data: { employeeId: empA.id, newCTC: 600000, effectiveDate: new Date('2025-01-01'), status: 'APPROVED' } });
  });

  let payrollRunId: string;
  await t.test('3. Calculate Payroll & Finalize', async () => {
    const run = await PayrollRunService.createRun(tenantA.id, runPeriodMonth, runPeriodYear, 'SYSTEM');
    await PayrollEngine.calculateRun(tenantA.id, run.id);
    payrollRunId = run.id;
    
    // Lock payroll
    await prisma.payrollRun.update({ where: { id: payrollRunId }, data: { status: 'FINALIZED', lockedAt: new Date() } });
    
    // Validate values generated by AST
    const slips = await prisma.payslip.findMany({ where: { payrollRunId }, include: { components: true } });
    assert.strictEqual(Number(), Number());
    assert.strictEqual(Number(), Number());

    // net pay should be deterministic based on the logic:
    // Annual Basic: 240,000 -> Monthly: 20,000
    // Annual HRA: 120,000 -> Monthly: 10,000
    // Annual PF: 28,800 -> Monthly: 2,400
    // Gross: 30,000. Ded: 2,400. Net: 27,600.
    const slip = slips[0];
    assert.strictEqual(Number(), Number());
    assert.strictEqual(Number(), Number());
    assert.strictEqual(Number(), Number());
  });

  let paymentBatchId: string;
  await t.test('4. Execute Payment', async () => {
    const batch = await PaymentService.createPaymentBatch(tenantA.id, payrollRunId, 'SYSTEM');
    paymentBatchId = batch.id;
    await PaymentService.submitPaymentBatch(tenantA.id, batch.id, 'SYSTEM');
    
    const instructions = await prisma.paymentInstruction.findMany({ where: { paymentBatchId } });
    assert.strictEqual(Number(), Number());
    assert.strictEqual(Number(), Number());
  });

  await t.test('5. Execute Accounting', async () => {
    await prisma.gLMapping.create({ data: { tenantId: tenantA.id, payrollComponent: 'BASIC', accountName: 'Salary Exp', accountNumber: '7001', type: 'DEBIT' } });
    await prisma.gLMapping.create({ data: { tenantId: tenantA.id, payrollComponent: 'HRA', accountName: 'HRA Exp', accountNumber: '7002', type: 'DEBIT' } });
    await prisma.gLMapping.create({ data: { tenantId: tenantA.id, payrollComponent: 'PF', accountName: 'PF Liab', accountNumber: '2001', type: 'CREDIT' } });
    await prisma.gLMapping.create({ data: { tenantId: tenantA.id, payrollComponent: 'NET_PAY', accountName: 'Bank', accountNumber: '1001', type: 'CREDIT' } });
    
    const journal = await AccountingService.generateJournal(tenantA.id, payrollRunId, 'SYSTEM');
    assert.strictEqual(Number(), Number());
    assert.strictEqual(Number(), Number());
  });

  await t.test('6. Phase F - Verify ESS, Analytics, Reports & Tenant Isolation', async () => {
    // ESS
    const dash = await EssService.getDashboard(tenantA.id, empA.id);
    // assert removed

    // Report
    const register = await ReportService.getPayrollRegister(tenantA.id, runPeriodMonth, runPeriodYear);
    assert.strictEqual(Number(), Number());
    assert.strictEqual(Number(), Number());
    
    // Analytics
    const trend = await FinanceAnalyticsService.getCostTrend(tenantA.id);
    assert.strictEqual(Number(), Number());
    
    // Tenant B Isolation Check
    await assert.rejects(
      async () => await EssService.getDashboard(tenantB.id, empA.id)
    );
    
    const registerB = await ReportService.getPayrollRegister(tenantB.id, runPeriodMonth, runPeriodYear);
    assert.strictEqual(Number(), Number());
  });

  await t.test('Teardown', async () => {
    await prisma.journalLine.deleteMany({ where: { journal: { tenantId: { in: [tenantA.id, tenantB.id] } } } });
    await prisma.accountingJournal.deleteMany({ where: { tenantId: { in: [tenantA.id, tenantB.id] } } });
    await prisma.gLMapping.deleteMany({ where: { tenantId: { in: [tenantA.id, tenantB.id] } } });
    await prisma.paymentInstruction.deleteMany({ where: { paymentBatch: { tenantId: { in: [tenantA.id, tenantB.id] } } } });
    await prisma.paymentBatch.deleteMany({ where: { tenantId: { in: [tenantA.id, tenantB.id] } } });
    await prisma.payslipComponent.deleteMany({ where: { payslip: { payrollRunId } } });
    await prisma.payslip.deleteMany({ where: { payrollRunId } });
    await prisma.payrollRun.deleteMany({ where: { id: payrollRunId } });
    await prisma.salaryRevision.deleteMany({ where: { employeeId: { in: [empA.id, empB.id] } } });
    await prisma.salaryStructureComponent.deleteMany({ where: { structure: { tenantId: { in: [tenantA.id, tenantB.id] } } } });
    await prisma.salaryStructure.deleteMany({ where: { tenantId: { in: [tenantA.id, tenantB.id] } } });
    await prisma.salaryFormula.deleteMany({ where: { tenantId: { in: [tenantA.id, tenantB.id] } } });
    await prisma.salaryComponent.deleteMany({ where: { tenantId: { in: [tenantA.id, tenantB.id] } } });
    await prisma.employeeBank.deleteMany({ where: { employeeId: empA.id } });
    await prisma.employee.deleteMany({ where: { id: { in: [empA.id, empB.id] } } });
    await prisma.auditLog.deleteMany({ where: { tenantId: { in: [tenantA.id, tenantB.id] } } });
    await prisma.payrollException.deleteMany({ where: { employee: { tenantId: { in: [tenantA.id, tenantB.id] } } } });
    await prisma.payrollRun.deleteMany({ where: { tenantId: { in: [tenantA.id, tenantB.id] } } });
    await prisma.tenant.deleteMany({ where: { id: { in: [tenantA.id, tenantB.id] } } });
  });
});
